before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: dlJCW5LVNV6gA7nClMXSnkscUnXUv9C7rG3ZatUF/59eyKcFPvR9ZDPntdNIQY5SE0PCVtPolFurjexi4wDhjqurUzuWqPtoV6VT/Nmc8I7mW50Oh7yDtvS+hth0wEmiQ0DbyTbh2ORYtFmH/O7SrUGo+KMfp2xp5pT2kQKsnUNeSBMGju3UlyyJFtDe2x2+zPXVQa0PJcQwwMVW7O0ciXIS+vB/IUHWocJRQTGAKVFMyMBKUWcQG9laU9F3yUUyFDBgBoDOQb6T9kBkEknxDkw7ujBgyk9u0R0Ay2Vs4zW3+mwGLXC8AXyQXKbISXcUq7oZgWvK7ySSObcbY7LQpacz/+Evys3tLfSpL0gofTsQjV0WKTDFyJLYgGW/5HOXeyfXY2Xyss5H5077+8iQoi4GoQVGcnI9+tT+x8wembauJ/pEOlCrKExx++iUiWAojCok4k7xZ9P6x7I89QlHAJRL8lzfHhMdlBxWQ4b8B1I2e9Q/BcLwt6FGGMrW3dAd+PLJJj/UZWgnaWNRJcd9LelDwR3Yw8vqt5Wvy1vAhSsiO4erWuwzgcVIWTf+S1x3sQn/2NBPVMbhFMm7bLgt4ibp+1mEs3IKGda9KXp/Q4Gn1W68XcWlRCNXxXAk5AnACSOOnVGA82wZVog93XFCZ5zoEMkKZA2nk6Rg3aHCT0s= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
